name: CI/CD Pipeline - DevOps Cloud Project

on:
  push:
    branches: [ "main" ]

jobs:
  # ---- FASE DE INTEGRACIÓN CONTINUA (CI) ----
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Inicializar Node.js (Entorno de pruebas)
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar Dependencias y Simular Pruebas Unitarias
      run: |
        npm install express redis
        echo "Running basic syntax check..."
        node -c app.js
        echo "✅ Pruebas básicas aprobadas con éxito."

  # ---- FASE DE DESPLIEGUE CONTINUO (CD) ----
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Clonar el repositorio para el deploy
      uses: actions/checkout@v4

    - name: Desplegar en la VM de GCP vía SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: 'bsujuyh'
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          mkdir -p ~/app
          cd ~/app
          
          # Si la carpeta no tiene el repositorio Git clonado, lo clona limpio
          if [ ! -d ".git" ]; then
            git clone https://github.com/${{ github.repository }}.git .
          else
            # Si ya existe, descarga los cambios más recientes
            git pull origin main
          fi
          
          # Levantar la aplicación con Docker Compose de manera limpia
          docker compose down || true
          docker compose up -d --build
          
          echo "🚀 ¡Despliegue completado en Producción!"
